name: movies
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  dio: ^5.4.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  get_it: ^7.6.0
  injectable: 2.1.2
  mobx: ^2.3.3+2
  flutter_mobx: ^2.1.1
  mockito: ^5.3.2
  rxdart: ^0.28.0
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  flutter_screenutil: ^5.8.4
  flutter_easyloading: ^3.0.5

dev_dependencies:
  auto_route_generator: ^7.1.1
  build_runner: ^2.4.5
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: 2.1.6
  mobx_codegen: ^2.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - .env
