name: movies
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  get_it: ^7.6.0
  injectable: 2.1.2
  mobx: ^2.3.3+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.5
  injectable_generator: 2.1.6


flutter:
  uses-material-design: true